stages:
  - module-pipelines
  - infra-pipelines

frontend:
  stage: module-pipelines
  trigger:
    include:
      - "/frontend/.gitlab-ci.yml"
    strategy: depend
  only:
    changes:
      - frontend/**/*

backend:
  stage: module-pipelines
  trigger:
    include:
      - "/backend/.gitlab-ci.yml"
    strategy: depend
  only:
    changes:
      - backend/**/*

trigger_helm_pipeline:
  stage: infra-pipelines
  trigger:
    project: std-046-13/momo-store-infra
    branch: master
    strategy: depend
  variables:
    BACKEND_IMAGE: $CI_REGISTRY_IMAGE/backend:$CI_COMMIT_SHA
    FRONTEND_IMAGE: $CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_SHA
  only:
    changes:
      - frontend/**/*
      - backend/**/*
  